all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    security_mode: plaintext
preflight:
  hosts:
    10.0.0.68:
    10.0.1.79:
zookeeper:
  hosts:
    10.0.0.68:
    10.0.1.79:
broker:
  hosts:
    10.0.0.68:
      kafka:
        broker:
          id: 1
    10.0.1.79:
      kafka:
        broker:
          id: 2
schema-registry:
  hosts:
    10.0.0.68:
control-center:
  hosts:
    10.0.1.79:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: 10.0.0.68:8083
connect-distributed:
  hosts:
    10.0.0.68:
kafka-rest:
  hosts:
    10.0.0.68:
ksql:
  hosts:
    10.0.1.79:
