all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    security_mode: plaintext
preflight:
  hosts:
    ip-10-0-2-249.ap-southeast-2.compute.internal:
    ip-10-0-1-169.ap-southeast-2.compute.internal:
    ip-10-0-1-182.ap-southeast-2.compute.internal:
zookeeper:
  hosts:
    ip-10-0-2-249.ap-southeast-2.compute.internal:
    ip-10-0-1-169.ap-southeast-2.compute.internal:
    ip-10-0-1-182.ap-southeast-2.compute.internal:
broker:
  hosts:
    ip-10-0-2-249.ap-southeast-2.compute.internal:
      kafka:
        broker:
          id: 1
    ip-10-0-1-169.ap-southeast-2.compute.internal:
      kafka:
        broker:
          id: 2
    ip-10-0-1-182.ap-southeast-2.compute.internal:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    ip-10-0-2-249.ap-southeast-2.compute.internal:
control-center:
  hosts:
    ip-10-0-1-169.ap-southeast-2.compute.internal:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: ip-10-0-2-249.ap-southeast-2.compute.internal:8083
connect-distributed:
  hosts:
    ip-10-0-2-249.ap-southeast-2.compute.internal:
kafka-rest:
  hosts:
    ip-10-0-2-249.ap-southeast-2.compute.internal:
ksql:
  hosts:
    ip-10-0-1-169.ap-southeast-2.compute.internal:
