all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    security_mode: plaintext
preflight:
  hosts:
    10.0.1.104:
    10.0.2.76:
    10.0.1.50:
zookeeper:
  hosts:
    10.0.1.104:
broker:
  hosts:
    10.0.1.104:
      kafka:
        broker:
          id: 1
    10.0.2.76:
      kafka:
        broker:
          id: 2
    10.0.1.50:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    10.0.1.104:
control-center:
  hosts:
    10.0.1.104:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: localhost:8083
connect-distributed:
  hosts:
    10.0.1.104:
kafka-rest:
  hosts:
    10.0.1.104:
ksql:
  hosts:
    10.0.1.104:
