all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    security_mode: plaintext
preflight:
  hosts:
    10.0.1.187:
    10.0.2.174:
zookeeper:
  hosts:
    10.0.1.187:
    10.0.2.174:
broker:
  hosts:
    10.0.1.187:
      kafka:
        broker:
          id: 1
    10.0.2.174:
      kafka:
        broker:
          id: 2
schema-registry:
  hosts:
    10.0.1.187:
control-center:
  hosts:
    10.0.2.174:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: 10.0.1.187:8083
connect-distributed:
  hosts:
    10.0.1.187:
kafka-rest:
  hosts:
    10.0.1.187:
ksql:
  hosts:
    10.0.2.174:
