all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    security_mode: plaintext
preflight:
  hosts:
    10.0.2.154:
zookeeper:
  hosts:
    10.0.2.154:
broker:
  hosts:
    10.0.2.154:
      kafka:
        broker:
          id: 1
schema-registry:
  hosts:
    10.0.2.154:
control-center:
  hosts:
    10.0.2.154:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: localhost:8083
connect-distributed:
  hosts:
    10.0.2.154:
kafka-rest:
  hosts:
    10.0.2.154:
ksql:
  hosts:
    10.0.2.154:
