all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    security_mode: plaintext
preflight:
  hosts:
    10.0.2.148:
    10.0.1.17:
    10.0.1.150:
zookeeper:
  hosts:
    10.0.2.148:
    10.0.1.17:
    10.0.1.150:
broker:
  hosts:
    10.0.2.148:
      kafka:
        broker:
          id: 1
    10.0.1.17:
      kafka:
        broker:
          id: 2
    10.0.1.150:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    10.0.2.148:
control-center:
  hosts:
    10.0.2.148:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: localhost:8083
connect-distributed:
  hosts:
    10.0.2.148:
kafka-rest:
  hosts:
    10.0.2.148:
ksql:
  hosts:
    10.0.2.148:
